image: docker:latest

cache:
  key: "ALL"
  paths:
    - dist/

stages:
  - npmDevelopBuild
  - npmMasterBuild
  - imageBuildDevelop
  - imageBuildMaster

npm-develop-build:
  image: node:8.6.0
  stage: npmDevelopBuild
  script:
    - npm install --registry=https://registry.npm.taobao.org --cache=$HOME/.npm/.cache/cnpm --disturl=https://npm.taobao.org/dist --userconfig=$HOME/.cnpmrc
    - npm run build-test --registry=https://registry.npm.taobao.org --cache=$HOME/.npm/.cache/cnpm --disturl=https://npm.taobao.org/dist --userconfig=$HOME/.cnpmrc
  only:
    - develop

npm-master-build:
  image: node:8.6.0
  stage: npmMasterBuild
  script:
    - npm install --registry=https://registry.npm.taobao.org --cache=$HOME/.npm/.cache/cnpm --disturl=https://npm.taobao.org/dist --userconfig=$HOME/.cnpmrc
    - npm run build --registry=https://registry.npm.taobao.org --cache=$HOME/.npm/.cache/cnpm --disturl=https://npm.taobao.org/dist --userconfig=$HOME/.cnpmrc
  only:
    - master

npm-build-develop:
  stage: imageBuildDevelop
  script:
    - "current_date=$(TZ=Asia/Shanghai date +%m%d%H%M)"
    - "commit_sha=$CI_COMMIT_SHA"
    - "docker build -t $DOCKER_REGISTRY_TEST:5000/shop-supplier-fe-pro:$CI_COMMIT_REF_NAME-$current_date-${commit_sha:0:8} ."
    - "docker login -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY_TEST:5000"
    - "docker push $DOCKER_REGISTRY_TEST:5000/shop-supplier-fe-pro:$CI_COMMIT_REF_NAME-$current_date-${commit_sha:0:8}"
  only:
    - develop

npm-build-master:
  stage: imageBuildMaster
  script:
    - "mv -f ./config/nginx-prod.conf ./config/nginx.conf"
    - "current_date=$(TZ=Asia/Shanghai date +%m%d%H%M)"
    - "commit_sha=$CI_COMMIT_SHA"
    - "docker build -t $DOCKER_REGISTRY_PRO:5000/shop-supplier-fe-pro:$CI_COMMIT_REF_NAME-$current_date-${commit_sha:0:8} ."
    - "docker login -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY_PRO:5000"
    - "docker push $DOCKER_REGISTRY_PRO:5000/shop-supplier-fe-pro:$CI_COMMIT_REF_NAME-$current_date-${commit_sha:0:8}"
  only:
    - master
